[libdefaults]
    default_realm = PENGUARD.LOCAL
    dns_lookup_realm = false
    dns_lookup_kdc = false
    rdns = false
    ticket_lifetime = 24h
    renew_lifetime = 7d
    forwardable = true
    udp_preference_limit = 0
    default_ccache_name = FILE:/tmp/krb5cc_%{uid}
    allow_weak_crypto = true
    default_tkt_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 rc4-hmac
    default_tgs_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 rc4-hmac
    permitted_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 rc4-hmac

[realms]
    PENGUARD.LOCAL = {
        kdc = 192.168.56.10
        admin_server = 192.168.56.10
        default_domain = penguard.local
    }

[domain_realm]
    penguard.local = PENGUARD.LOCAL
    .penguard.local = PENGUARD.LOCAL
