#!/usr/bin/env bash
# Generate a .env file with strong random secrets for a fresh FortiDashboard
# deployment. Refuses to overwrite an existing .env unless --force is passed.
#
# Usage:
#   ./scripts/bootstrap-secrets.sh            # safe mode: aborts if .env exists
#   ./scripts/bootstrap-secrets.sh --force    # overwrite an existing .env
#
# The script is idempotent on dependencies: it only needs `openssl`. It never
# reads secrets from the network, never commits anything, and exits non-zero
# on any failure so CI/Make wrappers can rely on it.

set -euo pipefail

FORCE=0
if [[ "${1:-}" == "--force" ]]; then
  FORCE=1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"
EXAMPLE_FILE="${REPO_ROOT}/.env.example"

if [[ ! -f "${EXAMPLE_FILE}" ]]; then
  echo "error: ${EXAMPLE_FILE} not found — run this from a clean checkout." >&2
  exit 1
fi

if [[ -f "${ENV_FILE}" && "${FORCE}" -ne 1 ]]; then
  echo "error: ${ENV_FILE} already exists. Pass --force to overwrite." >&2
  echo "       (Existing secrets will be lost — back them up first if needed.)" >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "error: openssl is required to generate secrets." >&2
  exit 1
fi

rand_urlsafe() {
  # Base64url, no padding, length argument is the *byte* length before encoding.
  openssl rand -base64 "$1" | tr -d '\n=' | tr '/+' '_-'
}

rand_fernet() {
  # Fernet expects 32 raw bytes, base64-encoded (44 chars with padding).
  openssl rand -base64 32 | tr -d '\n'
}

SECRET_KEY="$(rand_urlsafe 48)"
TOKEN_ENCRYPTION_KEY="$(rand_fernet)"
KEYCLOAK_CLIENT_SECRET="$(rand_urlsafe 32)"
KC_BOOTSTRAP_ADMIN_PASSWORD="$(rand_urlsafe 24)"
POSTGRES_PASSWORD="$(rand_urlsafe 24)"

umask 077  # ensure the file is created mode 600

cat > "${ENV_FILE}" <<EOF
# Generated by scripts/bootstrap-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT this file. .gitignore already lists .env, but double-check.

# --- Database ---
POSTGRES_USER=fortidashboard
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=fortidashboard
DATABASE_URL=postgresql://\${POSTGRES_USER}:\${POSTGRES_PASSWORD}@localhost:5432/\${POSTGRES_DB}
FORTIDASHBOARD_DATABASE_URL=postgresql+psycopg://fortidashboard:${POSTGRES_PASSWORD}@db:5432/fortidashboard

# --- Cockpit ports ---
API_HOST=http://localhost:8000
FRONTEND_URL=http://localhost:5173
FORTIDASHBOARD_API_PORT=8000
FORTIDASHBOARD_WEB_PORT=5173
FORTIDASHBOARD_KEYCLOAK_PORT=8080
FORTIDASHBOARD_POSTGRES_PORT=5432
FORTIDASHBOARD_REDIS_PORT=6379

# --- BFF secrets (rotate via bootstrap-secrets.sh --force) ---
FORTIDASHBOARD_SECRET_KEY=${SECRET_KEY}
FORTIDASHBOARD_TOKEN_ENCRYPTION_KEY=${TOKEN_ENCRYPTION_KEY}
FORTIDASHBOARD_MOCK_MODE=false
FORTIDASHBOARD_SESSION_COOKIE_NAME=fortidashboard_session
FORTIDASHBOARD_SESSION_COOKIE_SECURE=false
FORTIDASHBOARD_CSRF_COOKIE_NAME=fortidashboard_csrf
FORTIDASHBOARD_CSRF_HEADER_NAME=X-CSRF-Token
FORTIDASHBOARD_AUTH_RATE_LIMIT_MAX_ATTEMPTS=10
FORTIDASHBOARD_AUTH_RATE_LIMIT_WINDOW_SECONDS=60

# --- Keycloak ---
KC_BOOTSTRAP_ADMIN_USERNAME=admin
KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
FORTIDASHBOARD_KEYCLOAK_BASE_URL=http://localhost:8080
FORTIDASHBOARD_KEYCLOAK_REALM=fortidashboard
FORTIDASHBOARD_KEYCLOAK_CLIENT_ID=fortidashboard-bff
FORTIDASHBOARD_KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}

# --- SOC-lite services ---
FORTIDASHBOARD_SIEM_KOWALSKI_URL=http://siem-kowalski:8000
FORTIDASHBOARD_SOAR_SKIPPER_URL=http://soar-skipper:8000
FORTIDASHBOARD_XDR_RICO_URL=http://xdr-rico:8000
SIEM_KOWALSKI_DATABASE_URL=postgresql+psycopg://fortidashboard:${POSTGRES_PASSWORD}@db:5432/fortidashboard
SOAR_SKIPPER_DATABASE_URL=postgresql+psycopg://fortidashboard:${POSTGRES_PASSWORD}@db:5432/fortidashboard
XDR_RICO_DATABASE_URL=postgresql+psycopg://fortidashboard:${POSTGRES_PASSWORD}@db:5432/fortidashboard
EOF

chmod 600 "${ENV_FILE}"

cat <<EOF
.env written to ${ENV_FILE}

Summary (values redacted):
  POSTGRES_PASSWORD            = <24 bytes urlsafe>
  FORTIDASHBOARD_SECRET_KEY    = <48 bytes urlsafe>
  FORTIDASHBOARD_TOKEN_ENCRYPTION_KEY = <fernet, 32 raw bytes base64>
  FORTIDASHBOARD_KEYCLOAK_CLIENT_SECRET = <32 bytes urlsafe>
  KC_BOOTSTRAP_ADMIN_PASSWORD  = <24 bytes urlsafe>

Next steps:
  1. Review the .env file. Adjust hostnames/ports if your topology differs.
  2. Run: docker compose up -d --build
  3. Rotate again with: ./scripts/bootstrap-secrets.sh --force
EOF
