<#
.SYNOPSIS
    Generate a .env file with strong random secrets for a fresh FortiDashboard
    deployment.

.DESCRIPTION
    PowerShell mirror of scripts/bootstrap-secrets.sh. Refuses to overwrite an
    existing .env unless -Force is passed.

.EXAMPLE
    PS> ./scripts/bootstrap-secrets.ps1
    PS> ./scripts/bootstrap-secrets.ps1 -Force
#>

[CmdletBinding()]
param(
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$EnvFile = Join-Path $RepoRoot '.env'
$ExampleFile = Join-Path $RepoRoot '.env.example'

if (-not (Test-Path $ExampleFile)) {
    throw ".env.example not found at $ExampleFile — run this from a clean checkout."
}

if ((Test-Path $EnvFile) -and -not $Force) {
    Write-Error ".env already exists at $EnvFile. Pass -Force to overwrite."
    Write-Error '  (Existing secrets will be lost — back them up first if needed.)'
    exit 1
}

function New-UrlSafeSecret {
    param([int]$ByteLength)
    $bytes = New-Object byte[] $ByteLength
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $b64 = [Convert]::ToBase64String($bytes)
    return $b64.TrimEnd('=').Replace('/', '_').Replace('+', '-')
}

function New-FernetKey {
    # Fernet expects 32 raw bytes, base64-encoded (with padding).
    $bytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return [Convert]::ToBase64String($bytes)
}

$SecretKey                = New-UrlSafeSecret -ByteLength 48
$TokenEncryptionKey       = New-FernetKey
$KeycloakClientSecret     = New-UrlSafeSecret -ByteLength 32
$KcBootstrapAdminPassword = New-UrlSafeSecret -ByteLength 24
$PostgresPassword         = New-UrlSafeSecret -ByteLength 24

$ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

$content = @"
# Generated by scripts/bootstrap-secrets.ps1 on $ts
# DO NOT COMMIT this file. .gitignore already lists .env, but double-check.

# --- Database ---
POSTGRES_USER=fortidashboard
POSTGRES_PASSWORD=$PostgresPassword
POSTGRES_DB=fortidashboard
DATABASE_URL=postgresql://`${POSTGRES_USER}:`${POSTGRES_PASSWORD}@localhost:5432/`${POSTGRES_DB}
FORTIDASHBOARD_DATABASE_URL=postgresql+psycopg://fortidashboard:$PostgresPassword@db:5432/fortidashboard

# --- Cockpit ports ---
API_HOST=http://localhost:8000
FRONTEND_URL=http://localhost:5173
FORTIDASHBOARD_API_PORT=8000
FORTIDASHBOARD_WEB_PORT=5173
FORTIDASHBOARD_KEYCLOAK_PORT=8080
FORTIDASHBOARD_POSTGRES_PORT=5432
FORTIDASHBOARD_REDIS_PORT=6379

# --- BFF secrets (rotate via bootstrap-secrets.ps1 -Force) ---
FORTIDASHBOARD_SECRET_KEY=$SecretKey
FORTIDASHBOARD_TOKEN_ENCRYPTION_KEY=$TokenEncryptionKey
FORTIDASHBOARD_MOCK_MODE=false
FORTIDASHBOARD_SESSION_COOKIE_NAME=fortidashboard_session
FORTIDASHBOARD_SESSION_COOKIE_SECURE=false
FORTIDASHBOARD_CSRF_COOKIE_NAME=fortidashboard_csrf
FORTIDASHBOARD_CSRF_HEADER_NAME=X-CSRF-Token
FORTIDASHBOARD_AUTH_RATE_LIMIT_MAX_ATTEMPTS=10
FORTIDASHBOARD_AUTH_RATE_LIMIT_WINDOW_SECONDS=60

# --- Keycloak ---
KC_BOOTSTRAP_ADMIN_USERNAME=admin
KC_BOOTSTRAP_ADMIN_PASSWORD=$KcBootstrapAdminPassword
FORTIDASHBOARD_KEYCLOAK_BASE_URL=http://localhost:8080
FORTIDASHBOARD_KEYCLOAK_REALM=fortidashboard
FORTIDASHBOARD_KEYCLOAK_CLIENT_ID=fortidashboard-bff
FORTIDASHBOARD_KEYCLOAK_CLIENT_SECRET=$KeycloakClientSecret

# --- SOC-lite services ---
FORTIDASHBOARD_SIEM_KOWALSKI_URL=http://siem-kowalski:8000
FORTIDASHBOARD_SOAR_SKIPPER_URL=http://soar-skipper:8000
FORTIDASHBOARD_XDR_RICO_URL=http://xdr-rico:8000
SIEM_KOWALSKI_DATABASE_URL=postgresql+psycopg://fortidashboard:$PostgresPassword@db:5432/fortidashboard
SOAR_SKIPPER_DATABASE_URL=postgresql+psycopg://fortidashboard:$PostgresPassword@db:5432/fortidashboard
XDR_RICO_DATABASE_URL=postgresql+psycopg://fortidashboard:$PostgresPassword@db:5432/fortidashboard

# --- AI provider ---
# Default "scripted" works offline. Swap to a real model with one of the
# recipes below. Compose must list these vars in the api environment block
# (already done) for them to reach the container.
FORTIDASHBOARD_AI_PROVIDER=scripted
FORTIDASHBOARD_AI_API_KEY=
FORTIDASHBOARD_AI_MODEL=
FORTIDASHBOARD_AI_BASE_URL=
#
# Gemini via OpenAI-compat (key: https://aistudio.google.com/apikey):
# FORTIDASHBOARD_AI_PROVIDER=openai_compat
# FORTIDASHBOARD_AI_API_KEY=AIza...
# FORTIDASHBOARD_AI_MODEL=gemini-2.5-flash
# FORTIDASHBOARD_AI_BASE_URL=https://generativelanguage.googleapis.com/v1beta/openai
#
# Anthropic (key: https://console.anthropic.com):
# FORTIDASHBOARD_AI_PROVIDER=anthropic
# FORTIDASHBOARD_AI_API_KEY=sk-ant-...
# FORTIDASHBOARD_AI_MODEL=claude-haiku-4-5-20251001
# FORTIDASHBOARD_AI_BASE_URL=https://api.anthropic.com
"@

# Write without BOM, LF endings, and tighten ACLs to current user only.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($EnvFile, ($content -replace "`r`n", "`n"), $utf8NoBom)

try {
    $acl = Get-Acl $EnvFile
    $acl.SetAccessRuleProtection($true, $false)
    $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
        [System.Security.Principal.WindowsIdentity]::GetCurrent().Name,
        'FullControl', 'Allow'
    )
    $acl.SetAccessRule($rule)
    Set-Acl -Path $EnvFile -AclObject $acl
} catch {
    Write-Warning "Could not tighten ACL on $EnvFile (continuing): $_"
}

Write-Host ".env written to $EnvFile"
Write-Host ''
Write-Host 'Summary (values redacted):'
Write-Host '  POSTGRES_PASSWORD                  = <24 bytes urlsafe>'
Write-Host '  FORTIDASHBOARD_SECRET_KEY          = <48 bytes urlsafe>'
Write-Host '  FORTIDASHBOARD_TOKEN_ENCRYPTION_KEY = <fernet, 32 raw bytes base64>'
Write-Host '  FORTIDASHBOARD_KEYCLOAK_CLIENT_SECRET = <32 bytes urlsafe>'
Write-Host '  KC_BOOTSTRAP_ADMIN_PASSWORD        = <24 bytes urlsafe>'
Write-Host ''
Write-Host 'Next steps:'
Write-Host '  1. Review the .env file. Adjust hostnames/ports if needed.'
Write-Host '  2. Run: docker compose up -d --build'
Write-Host '  3. Rotate again with: ./scripts/bootstrap-secrets.ps1 -Force'
