#!/usr/bin/env bash
# Generate a .env file with strong random secrets for a fresh Penguard
# deployment. Refuses to overwrite an existing .env unless --force is passed.
#
# Usage:
#   ./scripts/bootstrap-secrets.sh            # safe mode: aborts if .env exists
#   ./scripts/bootstrap-secrets.sh --force    # overwrite an existing .env
#
# The script is idempotent on dependencies: it only needs `openssl`. It never
# reads secrets from the network, never commits anything, and exits non-zero
# on any failure so CI/Make wrappers can rely on it.

set -euo pipefail

FORCE=0
if [[ "${1:-}" == "--force" ]]; then
  FORCE=1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"
EXAMPLE_FILE="${REPO_ROOT}/.env.example"

if [[ ! -f "${EXAMPLE_FILE}" ]]; then
  echo "error: ${EXAMPLE_FILE} not found — run this from a clean checkout." >&2
  exit 1
fi

if [[ -f "${ENV_FILE}" && "${FORCE}" -ne 1 ]]; then
  echo "error: ${ENV_FILE} already exists. Pass --force to overwrite." >&2
  echo "       (Existing secrets will be lost — back them up first if needed.)" >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "error: openssl is required to generate secrets." >&2
  exit 1
fi

rand_urlsafe() {
  # Base64url, no padding, length argument is the *byte* length before encoding.
  openssl rand -base64 "$1" | tr -d '\n=' | tr '/+' '_-'
}

rand_fernet() {
  # Fernet expects 32 raw bytes, base64-encoded (44 chars with padding).
  openssl rand -base64 32 | tr -d '\n'
}

SECRET_KEY="$(rand_urlsafe 48)"
TOKEN_ENCRYPTION_KEY="$(rand_fernet)"
KEYCLOAK_CLIENT_SECRET="$(rand_urlsafe 32)"
KC_BOOTSTRAP_ADMIN_PASSWORD="$(rand_urlsafe 24)"
POSTGRES_PASSWORD="$(rand_urlsafe 24)"

prefer_non_loopback_ip() {
  while IFS= read -r candidate; do
    case "${candidate}" in
      ""|127.*|169.254.*|0.*) continue ;;
      *) printf '%s' "${candidate}"; return 0 ;;
    esac
  done
}

# Best-effort FortiGate-reachable host/IP for syslog forwarding. Operators can
# still override it in .env when the dashboard is behind NAT, a reverse proxy,
# or a different management network.
FORTIGATE_SYSLOG_PUBLIC_HOST="$(
  {
    if command -v ip >/dev/null 2>&1; then
      ip route get 1.1.1.1 2>/dev/null | tr ' ' '\n' | awk 'prev == "src" { print; exit } { prev = $0 }'
    fi
    hostname -I 2>/dev/null | tr ' ' '\n'
  } | prefer_non_loopback_ip
)"

umask 077  # ensure the file is created mode 600

cat > "${ENV_FILE}" <<EOF
# Generated by scripts/bootstrap-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT this file. .gitignore already lists .env, but double-check.

# --- Database ---
POSTGRES_USER=penguard
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=penguard
DATABASE_URL=postgresql://\${POSTGRES_USER}:\${POSTGRES_PASSWORD}@localhost:5432/\${POSTGRES_DB}
PENGUARD_DATABASE_URL=postgresql+psycopg://penguard:${POSTGRES_PASSWORD}@db:5432/penguard

# --- Cockpit ports ---
API_HOST=http://localhost:8000
FRONTEND_URL=http://localhost:5173
PENGUARD_API_PORT=8000
PENGUARD_WEB_PORT=5173
PENGUARD_KEYCLOAK_PORT=8080
PENGUARD_POSTGRES_PORT=5432
PENGUARD_REDIS_PORT=6379

# --- BFF secrets (rotate via bootstrap-secrets.sh --force) ---
PENGUARD_SECRET_KEY=${SECRET_KEY}
PENGUARD_TOKEN_ENCRYPTION_KEY=${TOKEN_ENCRYPTION_KEY}
PENGUARD_MOCK_MODE=false
PENGUARD_SESSION_COOKIE_NAME=penguard_session
PENGUARD_SESSION_COOKIE_SECURE=false
PENGUARD_SESSION_COOKIE_SAMESITE=lax
PENGUARD_SESSION_COOKIE_HTTPONLY=true
PENGUARD_CSRF_COOKIE_NAME=penguard_csrf
PENGUARD_CSRF_HEADER_NAME=X-CSRF-Token
PENGUARD_AUTH_RATE_LIMIT_MAX_ATTEMPTS=10
PENGUARD_AUTH_RATE_LIMIT_WINDOW_SECONDS=60

# --- Keycloak ---
KC_BOOTSTRAP_ADMIN_USERNAME=admin
KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
PENGUARD_KEYCLOAK_BASE_URL=http://localhost:8080
PENGUARD_KEYCLOAK_INTERNAL_BASE_URL=http://keycloak:8080
PENGUARD_KEYCLOAK_BROWSER_BASE_URL=http://localhost:8080
PENGUARD_KEYCLOAK_REALM=penguard
PENGUARD_KEYCLOAK_CLIENT_ID=penguard-bff
PENGUARD_KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
PENGUARD_KEYCLOAK_VERIFY_SSL=false
PENGUARD_KEYTAB_PATH=./infra/keycloak/empty-keytab.placeholder

# --- Browser-facing SSO URLs ---
PENGUARD_OIDC_ISSUER=http://localhost:8080/realms/penguard
PENGUARD_SSO_REDIRECT_URI=http://localhost:8000/api/auth/sso/kerberos/callback
PENGUARD_SSO_POST_LOGIN_URL=http://localhost:5173/
PENGUARD_SSO_FAILURE_REDIRECT_URL=http://localhost:5173/login

# --- SOC-lite services ---
PENGUARD_SIEM_KOWALSKI_URL=http://siem-kowalski:8000
PENGUARD_SOAR_SKIPPER_URL=http://soar-skipper:8000
PENGUARD_XDR_RICO_URL=http://xdr-rico:8000
PENGUARD_FORTIGATE_INGESTION_SCHEDULER_ENABLED=false
PENGUARD_FORTIGATE_INGESTION_SCHEDULER_TICK_SECONDS=10
PENGUARD_FORTIGATE_INGESTION_DEFAULT_INTERVAL_SECONDS=30
PENGUARD_FORTIGATE_INGESTION_MIN_INTERVAL_SECONDS=10
PENGUARD_FORTIGATE_INGESTION_MAX_INTERVAL_SECONDS=3600
# UDP syslog collector binds inside the API container. PUBLIC_HOST is the
# FortiGate-reachable host/IP. Bootstrap detects a best-effort local LAN IP;
# override it in .env when using NAT, a reverse proxy, or another network.
PENGUARD_FORTIGATE_SYSLOG_COLLECTOR_HOST=0.0.0.0
PENGUARD_FORTIGATE_SYSLOG_COLLECTOR_PUBLIC_HOST=${FORTIGATE_SYSLOG_PUBLIC_HOST}
PENGUARD_FORTIGATE_SYSLOG_COLLECTOR_PORT=5514
PENGUARD_ENABLE_LAB_DEMO_TOOLS=false
SIEM_KOWALSKI_DATABASE_URL=postgresql+psycopg://penguard:${POSTGRES_PASSWORD}@db:5432/penguard
SOAR_SKIPPER_DATABASE_URL=postgresql+psycopg://penguard:${POSTGRES_PASSWORD}@db:5432/penguard
XDR_RICO_DATABASE_URL=postgresql+psycopg://penguard:${POSTGRES_PASSWORD}@db:5432/penguard

# --- AI provider ---
# Default "scripted" works offline. Swap to a real model with one of the
# recipes below. Compose must list these vars in the api environment block
# (already done) for them to reach the container.
PENGUARD_AI_PROVIDER=scripted
PENGUARD_AI_API_KEY=
PENGUARD_AI_MODEL=
PENGUARD_AI_BASE_URL=
#
# Gemini via OpenAI-compat (key: https://aistudio.google.com/apikey):
# PENGUARD_AI_PROVIDER=openai_compat
# PENGUARD_AI_API_KEY=AIza...
# PENGUARD_AI_MODEL=gemini-2.5-flash
# PENGUARD_AI_BASE_URL=https://generativelanguage.googleapis.com/v1beta/openai
#
# Anthropic (key: https://console.anthropic.com):
# PENGUARD_AI_PROVIDER=anthropic
# PENGUARD_AI_API_KEY=sk-ant-...
# PENGUARD_AI_MODEL=claude-haiku-4-5-20251001
# PENGUARD_AI_BASE_URL=https://api.anthropic.com
EOF

chmod 600 "${ENV_FILE}"

cat <<EOF
.env written to ${ENV_FILE}

Summary (values redacted):
  POSTGRES_PASSWORD            = <24 bytes urlsafe>
  PENGUARD_SECRET_KEY    = <48 bytes urlsafe>
  PENGUARD_TOKEN_ENCRYPTION_KEY = <fernet, 32 raw bytes base64>
  PENGUARD_KEYCLOAK_CLIENT_SECRET = <32 bytes urlsafe>
  KC_BOOTSTRAP_ADMIN_PASSWORD  = <24 bytes urlsafe>

Next steps:
  1. Review the .env file. Adjust hostnames/ports if your topology differs.
  2. Run: docker compose up -d --build
  3. Rotate again with: ./scripts/bootstrap-secrets.sh --force
EOF
