<#
.SYNOPSIS
    Generate a .env file with strong random secrets for a fresh Penguard
    deployment.

.DESCRIPTION
    PowerShell mirror of scripts/bootstrap-secrets.sh. Refuses to overwrite an
    existing .env unless -Force is passed.

.EXAMPLE
    PS> ./scripts/bootstrap-secrets.ps1
    PS> ./scripts/bootstrap-secrets.ps1 -Force
#>

[CmdletBinding()]
param(
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$EnvFile = Join-Path $RepoRoot '.env'
$ExampleFile = Join-Path $RepoRoot '.env.example'

if (-not (Test-Path $ExampleFile)) {
    throw ".env.example not found at $ExampleFile - run this from a clean checkout."
}

if ((Test-Path $EnvFile) -and -not $Force) {
    Write-Error ".env already exists at $EnvFile. Pass -Force to overwrite."
    Write-Error '  (Existing secrets will be lost - back them up first if needed.)'
    exit 1
}

function New-UrlSafeSecret {
    param([int]$ByteLength)
    $bytes = New-Object byte[] $ByteLength
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    $b64 = [Convert]::ToBase64String($bytes)
    return $b64.TrimEnd('=').Replace('/', '_').Replace('+', '-')
}

function New-FernetKey {
    # Fernet expects 32 raw bytes, base64-encoded (with padding).
    $bytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    return [Convert]::ToBase64String($bytes)
}

$SecretKey                = New-UrlSafeSecret -ByteLength 48
$TokenEncryptionKey       = New-FernetKey
$KeycloakClientSecret     = New-UrlSafeSecret -ByteLength 32
$KcBootstrapAdminPassword = New-UrlSafeSecret -ByteLength 24
$PostgresPassword         = New-UrlSafeSecret -ByteLength 24

function Get-FortiGateSyslogPublicHost {
    try {
        $defaultRoute = Get-NetRoute -DestinationPrefix '0.0.0.0/0' -ErrorAction Stop |
            Sort-Object RouteMetric, InterfaceMetric |
            Select-Object -First 1
        if ($defaultRoute) {
            $ip = Get-NetIPAddress -AddressFamily IPv4 -InterfaceIndex $defaultRoute.InterfaceIndex -ErrorAction Stop |
                Where-Object { $_.IPAddress -notlike '127.*' -and $_.IPAddress -notlike '169.254.*' -and $_.IPAddress -notlike '0.*' } |
                Select-Object -First 1 -ExpandProperty IPAddress
            if ($ip) { return $ip }
        }
    } catch {
        # Fall through to the generic adapter scan below.
    }

    try {
        $ip = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction Stop |
            Where-Object { $_.IPAddress -notlike '127.*' -and $_.IPAddress -notlike '169.254.*' -and $_.IPAddress -notlike '0.*' } |
            Select-Object -First 1 -ExpandProperty IPAddress
        if ($ip) { return $ip }
    } catch {
        # Keep bootstrap portable; operator can fill the value manually.
    }

    return ''
}

$FortiGateSyslogPublicHost = Get-FortiGateSyslogPublicHost

$ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

$content = @"
# Generated by scripts/bootstrap-secrets.ps1 on $ts
# DO NOT COMMIT this file. .gitignore already lists .env, but double-check.

# --- Database ---
POSTGRES_USER=penguard
POSTGRES_PASSWORD=$PostgresPassword
POSTGRES_DB=penguard
DATABASE_URL=postgresql://`${POSTGRES_USER}:`${POSTGRES_PASSWORD}@localhost:5432/`${POSTGRES_DB}
PENGUARD_DATABASE_URL=postgresql+psycopg://penguard:$PostgresPassword@db:5432/penguard

# --- Cockpit ports ---
API_HOST=http://localhost:8000
FRONTEND_URL=http://localhost:5173
PENGUARD_API_PORT=8000
PENGUARD_WEB_PORT=5173
PENGUARD_KEYCLOAK_PORT=8080
PENGUARD_POSTGRES_PORT=5432
PENGUARD_REDIS_PORT=6379

# --- BFF secrets (rotate via bootstrap-secrets.ps1 -Force) ---
PENGUARD_SECRET_KEY=$SecretKey
PENGUARD_TOKEN_ENCRYPTION_KEY=$TokenEncryptionKey
PENGUARD_MOCK_MODE=false
PENGUARD_SESSION_COOKIE_NAME=penguard_session
PENGUARD_SESSION_COOKIE_SECURE=false
PENGUARD_SESSION_COOKIE_SAMESITE=lax
PENGUARD_SESSION_COOKIE_HTTPONLY=true
PENGUARD_CSRF_COOKIE_NAME=penguard_csrf
PENGUARD_CSRF_HEADER_NAME=X-CSRF-Token
PENGUARD_AUTH_RATE_LIMIT_MAX_ATTEMPTS=10
PENGUARD_AUTH_RATE_LIMIT_WINDOW_SECONDS=60

# --- Keycloak ---
KC_BOOTSTRAP_ADMIN_USERNAME=admin
KC_BOOTSTRAP_ADMIN_PASSWORD=$KcBootstrapAdminPassword
PENGUARD_KEYCLOAK_BASE_URL=http://localhost:8080
PENGUARD_KEYCLOAK_INTERNAL_BASE_URL=http://keycloak:8080
PENGUARD_KEYCLOAK_BROWSER_BASE_URL=http://localhost:8080
PENGUARD_KEYCLOAK_REALM=penguard
PENGUARD_KEYCLOAK_CLIENT_ID=penguard-bff
PENGUARD_KEYCLOAK_CLIENT_SECRET=$KeycloakClientSecret
PENGUARD_KEYCLOAK_VERIFY_SSL=false
PENGUARD_KEYTAB_PATH=./infra/keycloak/empty-keytab.placeholder

# --- Browser-facing SSO URLs ---
PENGUARD_OIDC_ISSUER=http://localhost:8080/realms/penguard
PENGUARD_SSO_REDIRECT_URI=http://localhost:8000/api/auth/sso/kerberos/callback
PENGUARD_SSO_POST_LOGIN_URL=http://localhost:5173/
PENGUARD_SSO_FAILURE_REDIRECT_URL=http://localhost:5173/login

# --- SOC-lite services ---
PENGUARD_SIEM_KOWALSKI_URL=http://siem-kowalski:8000
PENGUARD_SOAR_SKIPPER_URL=http://soar-skipper:8000
PENGUARD_XDR_RICO_URL=http://xdr-rico:8000
PENGUARD_FORTIGATE_INGESTION_SCHEDULER_ENABLED=false
PENGUARD_FORTIGATE_INGESTION_SCHEDULER_TICK_SECONDS=10
PENGUARD_FORTIGATE_INGESTION_DEFAULT_INTERVAL_SECONDS=30
PENGUARD_FORTIGATE_INGESTION_MIN_INTERVAL_SECONDS=10
PENGUARD_FORTIGATE_INGESTION_MAX_INTERVAL_SECONDS=3600
# UDP syslog collector binds inside the API container. PUBLIC_HOST is the
# FortiGate-reachable host/IP. Bootstrap detects a best-effort local LAN IP;
# override it in .env when using NAT, a reverse proxy, or another network.
PENGUARD_FORTIGATE_SYSLOG_COLLECTOR_HOST=0.0.0.0
PENGUARD_FORTIGATE_SYSLOG_COLLECTOR_PUBLIC_HOST=$FortiGateSyslogPublicHost
PENGUARD_FORTIGATE_SYSLOG_COLLECTOR_PORT=5514
PENGUARD_ENABLE_LAB_DEMO_TOOLS=false
SIEM_KOWALSKI_DATABASE_URL=postgresql+psycopg://penguard:$PostgresPassword@db:5432/penguard
SOAR_SKIPPER_DATABASE_URL=postgresql+psycopg://penguard:$PostgresPassword@db:5432/penguard
XDR_RICO_DATABASE_URL=postgresql+psycopg://penguard:$PostgresPassword@db:5432/penguard

# --- AI provider ---
# Default "scripted" works offline. Swap to a real model with one of the
# recipes below. Compose must list these vars in the api environment block
# (already done) for them to reach the container.
PENGUARD_AI_PROVIDER=scripted
PENGUARD_AI_API_KEY=
PENGUARD_AI_MODEL=
PENGUARD_AI_BASE_URL=
#
# Gemini via OpenAI-compat (key: https://aistudio.google.com/apikey):
# PENGUARD_AI_PROVIDER=openai_compat
# PENGUARD_AI_API_KEY=AIza...
# PENGUARD_AI_MODEL=gemini-2.5-flash
# PENGUARD_AI_BASE_URL=https://generativelanguage.googleapis.com/v1beta/openai
#
# Anthropic (key: https://console.anthropic.com):
# PENGUARD_AI_PROVIDER=anthropic
# PENGUARD_AI_API_KEY=sk-ant-...
# PENGUARD_AI_MODEL=claude-haiku-4-5-20251001
# PENGUARD_AI_BASE_URL=https://api.anthropic.com
"@

# Write without BOM, LF endings, and tighten ACLs to current user only.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($EnvFile, ($content -replace "`r`n", "`n"), $utf8NoBom)

try {
    $acl = Get-Acl $EnvFile
    $acl.SetAccessRuleProtection($true, $false)
    $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
        [System.Security.Principal.WindowsIdentity]::GetCurrent().Name,
        'FullControl', 'Allow'
    )
    $acl.SetAccessRule($rule)
    Set-Acl -Path $EnvFile -AclObject $acl
} catch {
    Write-Warning "Could not tighten ACL on $EnvFile (continuing): $_"
}

Write-Host ".env written to $EnvFile"
Write-Host ''
Write-Host 'Summary (values redacted):'
Write-Host '  POSTGRES_PASSWORD                  = <24 bytes urlsafe>'
Write-Host '  PENGUARD_SECRET_KEY          = <48 bytes urlsafe>'
Write-Host '  PENGUARD_TOKEN_ENCRYPTION_KEY = <fernet, 32 raw bytes base64>'
Write-Host '  PENGUARD_KEYCLOAK_CLIENT_SECRET = <32 bytes urlsafe>'
Write-Host '  KC_BOOTSTRAP_ADMIN_PASSWORD        = <24 bytes urlsafe>'
Write-Host ''
Write-Host 'Next steps:'
Write-Host '  1. Review the .env file. Adjust hostnames/ports if needed.'
Write-Host '  2. Run: docker compose up -d --build'
Write-Host '  3. Rotate again with: ./scripts/bootstrap-secrets.ps1 -Force'
